# Generated by Django 3.0 on 2024-08-09 10:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='count')),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_spares_related', related_query_name='created_spares', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_spares_related', related_query_name='updated_spares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='hours')),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_completedwork_related', related_query_name='created_completedwork', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_completedwork_related', related_query_name='updated_completedwork', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
