# Generated by Django 3.0 on 2025-01-30 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='completed_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spares',
            name='installation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='installation_date'),
            preserve_default=False,
        ),
    ]
