# Generated by Django 3.0 on 2025-01-30 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_auto_20250130_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='completed_date'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='installation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='installation_date'),
        ),
    ]
