# Generated by Django 3.0 on 2024-08-09 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('vin', models.CharField(max_length=20, unique=True, verbose_name='vin')),
                ('country', models.CharField(max_length=60, null=True, verbose_name='country')),
                ('manufacturer', models.CharField(max_length=50, null=True, verbose_name='manufacturer')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='model')),
                ('clas', models.CharField(max_length=50, null=True, verbose_name='class')),
                ('region', models.CharField(max_length=50, null=True, verbose_name='region')),
                ('wmi', models.CharField(max_length=50, null=True, verbose_name='wmi')),
                ('vds', models.CharField(max_length=50, null=True, verbose_name='vds')),
                ('vis', models.CharField(max_length=50, null=True, verbose_name='vis')),
                ('year', models.IntegerField(null=True, verbose_name='year')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_vehicle_related', related_query_name='created_vehicle', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_cars', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_vehicle_related', related_query_name='updated_vehicle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
