services:

   client:
     build:
       context: ./delorean
       dockerfile: ./Dockerfile
     ports:
       - 3000:3000
     depends_on:
       - server

   server:
       build:
         context: ./dmc
         dockerfile: ./Dockerfile.prod
       command: gunicorn dmc.wsgi:application --bind 0.0.0.0:8000
       volumes:
         - static_volume:/home/app/web/staticfiles
         - media_volume:/home/app/web/mediafiles
       expose:
         - 8000
       env_file:
         - ./dmc/.env.prod
       depends_on:
         - db

   db:
     image: postgres
     env_file:
       - ./dmc/.env.prod.db
     volumes:
       - postgres_data:/var/lib/postgresql/data/

   nginx:
     build: ./dmc/.nginx
     volumes:
       - static_volume:/home/app/web/staticfiles
       - media_volume:/home/app/web/mediafiles
     ports:
       - 1337:80
     depends_on:
       - server

volumes:
  postgres_data:
  static_volume:
  media_volume:
